CREATE DATABASE IF NOT EXISTS kentekens;

USE kentekens;

CREATE TABLE voertuigen (
                            kenteken VARCHAR(255),
                            voertuigsoort VARCHAR(255) NULL,
                            merk VARCHAR(255) NULL,
                            handelsbenaming VARCHAR(255) NULL,
                            vervaldatum_apk DATE NULL,
                            datum_tenaamstelling DATE NULL,
                            bruto_bpm DECIMAL(10, 2) NULL,
                            inrichting VARCHAR(255) NULL,
                            aantal_zitplaatsen INT NULL,
                            eerste_kleur VARCHAR(255) NULL,
                            tweede_kleur VARCHAR(255) NULL,
                            aantal_cilinders INT NULL,
                            cilinderinhoud INT NULL,
                            massa_ledig_voertuig INT NULL,
                            toegestane_maximum_massa_voertuig INT NULL,
                            massa_rijklaar INT NULL,
                            maximum_massa_trekken_ongeremd INT NULL,
                            maximum_trekken_massa_geremd INT NULL,
                            datum_eerste_toelating DATE NULL,
                            datum_eerste_tenaamstelling_in_nederland DATE NULL,
                            wacht_op_keuren VARCHAR(255) NULL,
                            catalogusprijs DECIMAL(10, 2) NULL,
                            wam_verzekerd VARCHAR(255) NULL,
                            maximale_constructiesnelheid INT NULL,
                            laadvermogen INT NULL,
                            oplegger_geremd INT NULL,
                            aanhangwagen_autonoom_geremd INT NULL,
                            aanhangwagen_middenas_geremd INT NULL,
                            aantal_staanplaatsen INT NULL,
                            aantal_deuren INT NULL,
                            aantal_wielen INT NULL,
                            afstand_hart_koppeling_tot_achterzijde_voertuig INT NULL,
                            afstand_voorzijde_voertuig_tot_hart_koppeling INT NULL,
                            afwijkende_maximum_snelheid INT NULL,
                            lengte INT NULL,
                            breedte INT NULL,
                            europese_voertuigcategorie VARCHAR(255) NULL,
                            europese_voertuigcategorie_toevoeging VARCHAR(255) NULL,
                            europese_uitvoeringcategorie_toevoeging VARCHAR(255) NULL,
                            plaats_chassisnummer VARCHAR(255) NULL,
                            technische_max_massa_voertuig INT NULL,
                            type VARCHAR(255) NULL,
                            type_gasinstallatie VARCHAR(255) NULL,
                            typegoedkeuringsnummer VARCHAR(255) NULL,
                            variant VARCHAR(255) NULL,
                            uitvoering VARCHAR(255) NULL,
                            volgnummer_wijziging_eu_typegoedkeuring VARCHAR(255) NULL,
                            vermogen_massarijklaar DECIMAL(10, 2) NULL,
                            wielbasis INT NULL,
                            export_indicator VARCHAR(255) NULL,
                            openstaande_terugroepactie_indicator VARCHAR(255) NULL,
                            vervaldatum_tachograaf DATE NULL,
                            taxi_indicator VARCHAR(255) NULL,
                            maximum_massa_samenstelling INT NULL,
                            aantal_rolstoelplaatsen INT NULL,
                            maximum_ondersteunende_snelheid INT NULL,
                            jaar_laatste_registratie_tellerstand INT NULL,
                            tellerstandoordeel VARCHAR(255) NULL,
                            code_toelichting_tellerstandoordeel VARCHAR(255) NULL,
                            tenaamstellen_mogelijk VARCHAR(255) NULL,
                            vervaldatum_apk_dt DATE NULL,
                            datum_tenaamstelling_dt DATE NULL,
                            datum_eerste_toelating_dt DATE NULL,
                            datum_eerste_tenaamstelling_in_nederland_dt DATE NULL,
                            vervaldatum_tachograaf_dt DATE NULL,
                            maximum_last_onder_de_vooras_sen_tezamen_koppeling INT NULL,
                            type_remsysteem_voertuig_code VARCHAR(255) NULL,
                            rupsonderstelconfiguratiecode VARCHAR(255) NULL,
                            wielbasis_voertuig_minimum INT NULL,
                            wielbasis_voertuig_maximum INT NULL,
                            lengte_voertuig_minimum INT NULL,
                            lengte_voertuig_maximum INT NULL,
                            breedte_voertuig_minimum INT NULL,
                            breedte_voertuig_maximum INT NULL,
                            hoogte_voertuig DECIMAL(10, 2) NULL,
                            hoogte_voertuig_minimum DECIMAL(10, 2) NULL,
                            hoogte_voertuig_maximum DECIMAL(10, 2) NULL,
                            massa_bedrijfsklaar_minimaal INT NULL,
                            massa_bedrijfsklaar_maximaal INT NULL,
                            technisch_toelaatbaar_massa_koppelpunt INT NULL,
                            maximum_massa_technisch_maximaal INT NULL,
                            maximum_massa_technisch_minimaal INT NULL,
                            subcategorie_nederland VARCHAR(255) NULL,
                            verticale_belasting_koppelpunt_getrokken_voertuig INT NULL,
                            zuinigheidsclassificatie VARCHAR(255) NULL,
                            registratie_datum_goedkeuring_afschrijvingsmoment_bpm DATE NULL,
                            registratie_datum_goedkeuring_afschrijvingsmoment_bpm_dt DATE NULL,
                            gem_lading_wrde DECIMAL(10, 2) NULL,
                            aerodyn_voorz VARCHAR(255) NULL,
                            massa_alt_aandr INT NULL,
                            verl_cab_ind VARCHAR(255) NULL,
                            api_gekentekende_voertuigen_assen VARCHAR(255) NULL,
                            api_gekentekende_voertuigen_brandstof VARCHAR(255) NULL,
                            api_gekentekende_voertuigen_carrosserie VARCHAR(255) NULL,
                            api_gekentekende_voertuigen_carrosserie_specifiek VARCHAR(255) NULL,
                            api_gekentekende_voertuigen_voertuigklasse VARCHAR(255) NULL,
                            PRIMARY KEY (`kenteken`)
);