services:
    db:
        image: mysql:5.7
        command: --max_connections=200000
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_DATABASE: kentekens
            MYSQL_USER: user
            MYSQL_PASSWORD: j9UWxMQN0bGlZpYIPLiw
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - backend

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ""
        depends_on:
            - db
        ports:
            - "8080:80"
        networks:
            - backend

volumes:
    db_data:

networks:
    backend:
        driver: bridge